prompts = [
    "Make her lounging on a luxurious yacht, wearing elegant sunglasses and a stylish summer dress, with the ocean's azure backdrop.",
    "Make her exploring an enchanting forest, dressed in casual hiking attire, with light filtering through the trees, casting a serene glow.",
    "Make her at a chic rooftop party in the city at dusk, wearing a glamorous evening gown, with city lights twinkling in the background.",
    "Make her riding a horse along a picturesque countryside trail, wearing equestrian gear, with a backdrop of rolling hills and a clear blue sky.",
    "Make her petting a giraffe at an exotic wildlife sanctuary, dressed in safari gear, with a look of wonder and excitement on her face.",
    "Make her practicing yoga in a tranquil park at sunrise, wearing workout attire, surrounded by nature and the early morning golden light.",
    "Make her walking through a vibrant street market in a foreign city, dressed in a colorful, flowy dress, exploring different stalls and cultural artifacts.",
    "Make her enjoying a cozy evening at home, wearing comfortable loungewear, with a book in hand and a warm, inviting fireplace in the background.",
    "Make her at a trendy coffee shop, casually dressed, sipping a latte and working on her laptop, with a bustling urban vibe around her.",
    "Make her painting in a sunlit art studio, wearing a smock splattered with paint, deeply engrossed in her creative process, with canvases and art supplies around.",
    "Make her attending a glamorous film premiere, wearing a dazzling red carpet gown, with flashes of paparazzi cameras and a crowd of fans in the background.",
    "Make her enjoying a beach bonfire at night, dressed in cozy beachwear, with friends, soft sand underfoot, and the gentle glow of the fire.",
    "Make her hiking in a snow-covered mountain landscape, wearing winter gear, with the beauty of snow-capped peaks and a clear blue sky around her.",
    "Make her experiencing the thrill of skydiving, in mid-air, wearing a skydiving suit and goggles, with a breathtaking aerial view of the landscape below.",
    "Make her engaging in a pottery making session in a rustic studio, wearing an apron, hands covered in clay, focused on shaping a beautiful piece.",
    "Make her strolling through a historic European city, wearing chic travel attire, with cobblestone streets, ancient buildings, and a charming café scene.",
    "Make her participating in a vibrant dance class, wearing fitness dancewear, full of energy and movement, with a group of people enjoying the rhythm.",
    "Make her relaxing in a hot air balloon, dressed in casual attire, with a panoramic view of a scenic landscape unfolding below at sunrise.",
    "Make her volunteering at an animal shelter, wearing simple, practical clothes, lovingly caring for puppies and kittens, with a look of compassion and joy.",
    "Make her attending a fashion show, dressed in a cutting-edge designer outfit, seated in the front row, with models walking the runway in the background.",
    "Make her savoring a gourmet meal at a high-end restaurant, dressed elegantly, with a beautifully presented dish in front of her and a sophisticated ambiance.",
    "Make her wandering through a lush botanical garden, wearing a flowery summer dress, surrounded by a diverse array of vibrant plants and flowers.",
    "Make her experiencing the thrill of a roller coaster ride at an amusement park, hair flying in the wind, with a background of colorful rides and excited crowds.",
    "Make her practicing archery in a serene forest setting, wearing sporty outdoor attire, focused intently on hitting the bullseye with a bow in hand.",
    "Make her snorkeling in a tropical coral reef, wearing a snorkel and swimsuit, surrounded by a multitude of colorful fish and underwater life.",
    "Make her painting a mural on an urban street wall, wearing casual clothes with a paintbrush in hand, contributing to a vibrant and artistic cityscape.",
    "Make her attending a poetry reading in a cozy bookstore café, dressed in bohemian chic attire, with shelves of books and an attentive audience around her.",
    "Make her participating in a traditional tea ceremony in Japan, wearing a beautiful kimono, with an atmosphere of calm and cultural richness.",
    "Make her enjoying a star-gazing session in a remote desert, lying on a blanket, dressed in warm night clothes, under a vast, star-filled sky.",
    "Make her at a vintage record store, browsing through classic albums, wearing a retro-inspired outfit, with a nostalgic, old-school vibe around her.",
    "Make her enjoying a picnic in a flower-filled meadow, wearing a sundress, with a picnic basket, blanket, and a beautiful landscape in the background.",
    "Make her exploring a bustling street market in a foreign country, wearing casual clothes, with colorful stalls and a vibrant cultural atmosphere around her.",
    "Make her enjoying a relaxing spa day, wearing a bathrobe, with a serene, tranquil ambiance, and a massage therapist pampering her with a facial.",
    "Make her attending a glamorous awards show, wearing a stunning red carpet gown, with a crowd of fans and photographers in the background.",
    "Make her enjoying a scenic bike ride through the countryside, wearing a helmet and athletic attire, with a backdrop of rolling hills and a clear blue sky.",
    "Make her enjoying a romantic gondola ride in Venice, wearing a stylish outfit, with a backdrop of beautiful Venetian architecture and a serene canal.",
    "Make her enjoying a peaceful afternoon at a botanical garden, wearing a sundress, with a variety of plants and flowers in the background.",
    "Make her enjoying a scenic train ride through the countryside, wearing a casual outfit, with a backdrop of rolling hills and a clear blue sky.",
    "Make her enjoying a relaxing day at the beach, wearing a swimsuit, with a backdrop of a beautiful ocean and a clear blue sky.",
    "Make her enjoying a scenic drive through the countryside, wearing a casual outfit, with a backdrop of rolling hills and a clear blue sky.",
    "Make her enjoying a peaceful afternoon at a park, wearing a sundress, with a backdrop of trees and a clear blue sky.",
    "Make her enjoying a scenic hike through the countryside, wearing a casual outfit, with a backdrop of rolling hills and a clear blue sky.",
]
